default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mad_development

test:
  <<: *default
  database: mad_test

production:
  <<: *default
  database: mad_production
  username: mad
  password: <%= ENV["MYAPP_ROR_DATABASE_PASSWORD"] %>
